[project]
name = "fd_tool"
version = "0.1"
requires-python = ">=3.12"
dependencies = [
    "semver>=3.0.4,<4",
]

[project.scripts]
fd_api = "fd_tool.scripts.fd_api:main"
fd_file_mgr = "fd_tool.scripts.fd_file_mgr:main"


[tool.setuptools.packages.find]
include = ["fd_tool*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
